version: "3.7"
services:
  tauri-playground:
    build:
      dockerfile: ./Dockerfile
    env_file:
      - ./.env.wslg
    restart: always
    tty: true
    volumes:
      - ../:/home/node/code
      - /mnt/wslg:/mnt/wslg
      - /tmp/.X11-unix:/tmp/.X11-unix
